name: utm_helper
description: UTM helper is a package that helps you to get UTM parameters from URL.
version: 0.0.1
homepage: https://github.com/viverya/utm-helper
repository: https://github.com/viverya/utm-helper

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0