name: utm_helper
description: UTM helper is a package that helps you to get UTM parameters from URL.
version: 0.0.5
homepage: https://github.com/viverya/utm-helper
repository: https://github.com/viverya/utm-helper
issue_tracker: https://github.com/viverya/utm-helper/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0